springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html

server:
  port: 8180

idGenerator:
  originId: event_management_agent_${EP_EVENT_MANAGEMENT_AGENT_ID}

spring:
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  main:
    allow-bean-definition-overriding: true

camel:
  springboot:
    use-mdc-logging: true
  errorHandling:
    maximumRedeliveries: 10
    maximumRedeliveryDelay: 60000
    redeliveryDelay: 1000

kafka:
  client:
    config:
      connections:
        timeout:
          value: 60_000
          unit: milliseconds
        max-idle:
          value: 10_000
          unit: milliseconds
        request-timeout:
          value: 5_000
          unit: milliseconds
      reconnections:
        backoff:
          value: 50
          unit: milliseconds
        max-backoff:
          value: 1_000
          unit: milliseconds

eventPortal:
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:defaultAgentId}
  organizationId: ${EP_ORGANIZATION_ID:defaultOrgId}
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  gateway:
    id: gateway
    name: evmr1
    messaging:
      standalone: true
      rtoSession: false
      enableHeartbeats: false
      testHeartbeats: false
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH}
          url: ${EP_GATEWAY_URL}
          msgVpn: ${EP_GATEWAY_MSGVPN}
          trustStoreDir: ${SSL_STORE_DIR}
          users:
            - name: messaging1
              username: ${EP_GATEWAY_USERNAME}
              password: ${EP_GATEWAY_PASSWORD}
              clientName: runtime_agent_${EP_RUNTIME_AGENT_ID}  # 'client_' + runtimeAgentId

# Below is an example of how to set up messaging service configuration in the application.yml file.

#plugins:
#  resources:
#    # Confluent Schema Registry No Auth example
#    - id: someConfluentId
#      name: no auth confluent example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#        - id2
#        - id3
#      connections:
#        - name: myConfluentNoAuth
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#    # Confluent Schema Registry Basic Auth example
#    - id: someConfluentId
#      name: no auth confluent example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#      connections:
#        - name: myConfluentBasicAuth
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#          authentication:
#            - protocol: BASIC
#              credentials:
#                - properties:
#                    - name: username
#                      value: ${CONFLUENT_USERNAME}
#                    - name: password
#                      value: ${CONFLUENT_PASSWORD}
#                  source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#    # Confluent Schema Registry Basic Auth With SSL example
#    - id: someConfluentId
#      name: no auth confluent example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#      connections:
#        - name: myConfluentBasicAuthWithSSL
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#          authentication:
#            - protocol: BASIC_SSL
#              credentials:
#                - properties:
#                    - name: username
#                      value: ${CONFLUENT_USERNAME}
#                    - name: password
#                      value: ${CONFLUENT_PASSWORD}
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                  source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#    # Confluent Schema Registry Basic Auth With mTLS example
#    - id: someConfluentId
#      name: Basic Auth With mTLS example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#      connections:
#        - name: myConfluentBasicAuthWithMTLS
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#          authentication:
#            - protocol: BASIC_MTLS
#              credentials:
#                - properties:
#                    - name: username
#                      value: ${CONFLUENT_USERNAME}
#                    - name: password
#                      value: ${CONFLUENT_PASSWORD}
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                    - name: ssl.keystore.location
#                      value: ${KEYSTORE_LOCATION}
#                    - name: ssl.keystore.password
#                      value: ${KEYSTORE_PASSWORD}
#                    - name: ssl.key.password
#                      value: ${KEY_PASSWORD}
#                  source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#    # Confluent Schema Registry TLS example
#    - id: someConfluentId
#      name: no auth confluent example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#      connections:
#        - name: myConfluentTLS
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#          authentication:
#            - protocol: TLS
#              credentials:
#                - properties:
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                  source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#    # Confluent Schema Registry MTLS example
#    - id: someConfluentId
#      name: no auth confluent example
#      type: confluent_schema_registry
#      relatedServices:
#        - id1
#      connections:
#        - name: myConfluentMTLS
#          url: ${CONFLUENT_SCHEMA_REGISTRY_URL}
#          authentication:
#            - protocol: MTLS
#              credentials:
#                - properties:
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                    - name: ssl.keystore.password
#                      value: ${KEYSTORE_PASSWORD}
#                    - name: ssl.keystore.location
#                      value: ${KEYSTORE_LOCATION}
#                    - name: ssl.key.password
#                      value: ${KEY_PASSWORD}
#                  source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#    # Solace example
#    - id: solaceDefaultService
#      type: SOLACE
#      name: staging service
#      connections:
#        - name: mySolaceServiceSemp
#          url: ${SOLACE_SEMP_URL}
#          authentication:
#            - protocol: SEMP
#              credentials:
#                - source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#                  properties:
#                    - name: username
#                      value: ${SOLACE_SEMP_USERNAME}
#                    - name: password
#                      value: ${SOLACE_SEMP_PASSWORD}
#          properties:
#            - name: msgVpn
#              value: ${SOLACE_VPN_NAME}
#            - name: sempPageSize
#              value: 100
#    # MTLS example
#    - id: kafkaMTLSServiceExample
#      name: mtls kafka cluster example
#      type: KAFKA
#      connections:
#        - name: kafkaMTLSConnection
#          url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:11091,kafka2:11092}
#          authentication:
#            - protocol: SSL
#              credentials:
#                - source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#                  properties:
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                    - name: ssl.keystore.password
#                      value: ${KEYSTORE_PASSWORD}
#                    - name: ssl.keystore.location
#                      value: ${KEYSTORE_LOCATION}
#                    - name: ssl.key.password
#                      value: ${KEY_PASSWORD}
#    # SASL SCRAM
#    - id: kafkaSASLSCRAMServiceExample
#      name: sasl scram kafka cluster example
#      type: KAFKA
#      connections:
#        - name: kafkaSASLSCRAMConnection
#          url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:14091,kafka2:14092}
#          authentication:
#            - protocol: SASL_SSL
#              credentials:
#                - source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: ALL
#                  properties:
#                    - name: ssl.truststore.location
#                      value: ${TRUSTSTORE_LOCATION}
#                    - name: ssl.truststore.password
#                      value: ${TRUSTSTORE_PASSWORD}
#                    - name: sasl.jaas.config
#                      value: org.apache.kafka.common.security.scram.ScramLoginModule required username=<username> password=<password>;
#                    - name: sasl.mechanism
#                      value: SCRAM-SHA-256
#      # SASL Plain example
#      - id: saslplain
#        name: saslplain
#        type: KAFKA
#        connections:
#          - name: saslplainconn
#            url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:9091,kafka2:9092}
#            authentication:
#              - protocol: SASL_PLAINTEXT
#                credentials:
#                  - source: ENVIRONMENT_VARIABLE
#                    operations:
#                      - name: ALL
#                    properties:
#                      - name: sasl.mechanism
#                        value: PLAIN
#                      - name: sasl.jaas.config
#                        value: org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>>" password="<password>";
#      # SASL Plain over SSL
#      - id: saslplainssl
#        name: saslplainssl
#        type: KAFKA
#        connections:
#          - name: saslplainsslconn
#            url: ${KAFKA_BOOTSTRAP_SERVERS:kafka1:13091,kafka2:13092}
#            authentication:
#              - protocol: SASL_SSL
#                credentials:
#                  - source: ENVIRONMENT_VARIABLE
#                    operations:
#                      - name: ALL
#                    properties:
#                      - name: ssl.truststore.location
#                        value: ${TRUSTSTORE_LOCATION}
#                      - name: sasl.mechanism
#                        value: PLAIN
#                      - name: sasl.jaas.config
#                        value: org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>>" password="<password>";
#      # AWS IAM Example.
#      # NOTE: Remember to set the aws access id and password in the environment or credentials!
#      - id: iam
#        name: iam
#        type: KAFKA
#        connections:
#          - name: iamConn
#            url: ${KAFKA_BOOTSTRAP_SERVERS:awsservers:9098}
#            authentication:
#              - protocol: SASL_SSL
#                credentials:
#                  - source: ENVIRONMENT_VARIABLE
#                    operations:
#                      - name: ALL
#                    properties:
#                      - name: ssl.truststore.location
#                        value: ${TRUSTSTORE_LOCATION}
#                      - name: security.protocol
#                        value: SASL_SSL
#                      - name: sasl.mechanism
#                        value: AWS_MSK_IAM
#                      - name: sasl.jaas.config
#                        value: software.amazon.msk.auth.iam.IAMLoginModule required;
#                      - name: sasl.client.callback.handler.class
#                        value: software.amazon.msk.auth.iam.IAMClientCallbackHandler
#      # IBM MQ Example
#    - id: ibmmqDefaultService
#      type: IBMMQ
#      name: IBM MQ Test Service
#      connections:
#        - name: IBMMQBroker
##          Example: https://[domain:[port]]/ibmmq/rest/v1/admin/qmgr/{qmgrName}
#          url: ${IBM_MQ_REST_API_URL}
#          authentication:
#            - protocol: BASIC
#              credentials:
#                - source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: IBMMQ_ALL
#                  properties:
#                    - name: username
#                      value: ${IBMMQ_ADMINISTRATOR_USERNAME}
#                    - name: password
#                      value: ${IBMMQ_ADMINISTRATOR_PASSWORD}
      # Tibco EMS Example
#    - id: tibcoEMSDefaultService
#      type: TIBCOEMS
#      name: EMS Test Service
#      connections:
#        - name: EMSBroker
##          tcp[s]://[domain:[port]]]
#          url: ${EMS_ADMIN_API_URL}
#          authentication:
#            - protocol: BASIC
#              credentials:
#                - source: ENVIRONMENT_VARIABLE
#                  operations:
#                    - name: TIBCOEMS_ALL
#                  properties:
#                    - name: username
#                      value: ${EMS_ADMINISTRATOR_USERNAME}
#                    - name: password
#                      value: ${EMS_ADMINISTRATOR_PASSWORD}
